---
version: 2.1

orbs:
  circleci-config: simpleviewinc/circleci-config@1

common_config: &common_config
  context: default
  filters:
    branches:
      only:
        - develop
        - master
        - qa
        - /pull.*/

workflows:
  build:
    jobs:
      - circleci-config/gce_build_deploy_kubernetes: *common_config
      - circleci-config/gce_test_kubernetes:
          <<: *common_config
          filters:
            branches:
              only: /pull.*/
          requires:
            - circleci-config/gce_build_deploy_kubernetes
      - circleci-config/complete:
          <<: *common_config
          requires:
            - circleci-config/gce_build_deploy_kubernetes
            - circleci-config/gce_test_kubernetes

